export type YijianCoverage = 'covered' | 'partial' | 'missing' | 'merged';
export type YijianPlatform = 'studio' | 'vision' | 'shared';
export type YijianPriority = 'P0' | 'P1' | 'P2';

export interface YijianDocComparisonItem {
  group: string;
  title: string;
  docPath: string;
  imageCount: number;
  auditEvidence: string;
  platform: YijianPlatform;
  mappedRoutes: string[];
  coverage: YijianCoverage;
  gap: string;
  implementation: string;
  priority: YijianPriority;
  acceptance: string;
}

export const yijianDocComparison: YijianDocComparisonItem[] = [
  {
    group: '功能更新记录',
    title: '功能更新记录',
    docPath: 'hmnssc0tu',
    imageCount: 0,
    auditEvidence: '已读取在线正文；该页无业务截图，作为版本更新影响清单承载。',
    platform: 'shared',
    mappedRoutes: ['/studio/explore/comparison'],
    coverage: 'covered',
    gap: '已在对标概览页按技能生产、导入导出、授权与安全、复核统计、视觉应用和平台治理归类展示更新影响。',
    implementation: '在对标概览页集中展示近期能力演进，并关联 Studio 与 Vision 模块。',
    priority: 'P1',
    acceptance: '更新记录能按模块归类展示，并能指向对应功能区。',
  },
  {
    group: '产品描述',
    title: '认识识界',
    docPath: 'Gmnssc0vv',
    imageCount: 0,
    auditEvidence: '已读取在线正文；该页无业务截图，提炼为双平台定位说明。',
    platform: 'shared',
    mappedRoutes: ['/studio/explore/comparison'],
    coverage: 'covered',
    gap: '已通过能力地图说明 Studio 负责技能/模型/数据/API，Vision 负责设备/监控/预警/SOP/视图分析。',
    implementation: '通过能力地图解释技能开发平台与视觉应用平台的边界。',
    priority: 'P0',
    acceptance: '页面能说明 Studio 负责技能/模型/数据/API，Vision 负责设备/监控/预警/SOP/视图分析。',
  },
  {
    group: '产品描述',
    title: '平台架构',
    docPath: 'Mmnssc11o',
    imageCount: 0,
    auditEvidence: '已读取在线正文；该页无业务截图，提炼为数据、模型、技能、应用架构链路。',
    platform: 'shared',
    mappedRoutes: ['/studio/explore/comparison'],
    coverage: 'covered',
    gap: '已通过端到端闭环和架构实体卡片展示设备、点位、技能、模型、数据、API、离线部署关系。',
    implementation: '在对标概览页用架构卡片和实体链路展示全局闭环。',
    priority: 'P0',
    acceptance: '能看出从数据湖到模型训练、技能编排、视觉应用和 API/离线部署的链路。',
  },
  {
    group: '技能开发 / 快速开始',
    title: '三分钟创建一个视觉AI技能',
    docPath: 'Mmnssc207',
    imageCount: 15,
    auditEvidence: '已读取正文和 15 张截图；流程为创建技能、待发布卡片、进入编排、发布。',
    platform: 'studio',
    mappedRoutes: ['/studio/explore/quick-start', '/studio/workspace/orchestrate'],
    coverage: 'covered',
    gap: '已通过快速开始页与编排入口展示基础信息、待发布技能卡片、进入画布、调试和发布链路。',
    implementation: '新增快速开始配置页，并在编排页强化节点参数与发布路径。',
    priority: 'P0',
    acceptance: '快速开始页展示基础信息 → 待发布技能卡片 → 进入编排画布 → 调试 → 发布 API/视觉应用四步流程。',
  },
  {
    group: '技能开发 / 快速开始',
    title: '基于模板快速迭代专属场景模型',
    docPath: 'Imnssc1y0',
    imageCount: 8,
    auditEvidence: '已读取正文和 8 张截图；流程为模板选择、数据集、训练、评测、模型入库。',
    platform: 'studio',
    mappedRoutes: ['/studio/explore/quick-start', '/studio/workspace/model-train/tasks'],
    coverage: 'covered',
    gap: '已通过快速开始页和训练任务页串联模板、数据集、标注、训练、评测和模型入库闭环。',
    implementation: '用快速开始页与训练任务 flowSteps 串联模板迭代流程。',
    priority: 'P0',
    acceptance: '能看到数据集、模板、训练任务、评测、模型入库的闭环。',
  },
  {
    group: '技能开发 / 快速开始',
    title: '技能广场',
    docPath: '7mnssc2za',
    imageCount: 0,
    auditEvidence: '已读取在线正文；该页无截图，重点为技能广场筛选、详情、添加。',
    platform: 'studio',
    mappedRoutes: ['/studio/explore/skills'],
    coverage: 'covered',
    gap: '已有技能广场，仍可补充版本、添加到视觉应用和导出授权语义。',
    implementation: '扩展卡片详情的来源、版本、适用场景和推荐流程文案。',
    priority: 'P1',
    acceptance: '技能卡片能说明行业、场景、版本和添加流程。',
  },
  {
    group: '技能开发 / 快速开始',
    title: '场景模型',
    docPath: 'xmnssc31o',
    imageCount: 3,
    auditEvidence: '已读取正文和 3 张截图；重点为场景模型体验、Prompt、上传样例与结果。',
    platform: 'studio',
    mappedRoutes: ['/studio/explore/scenes'],
    coverage: 'covered',
    gap: '已有多模态体验面板，可继续补充提示词和高级参数说明。',
    implementation: '保留现有体验区，补充 Prompt、阈值、上传图片与结果预览。',
    priority: 'P1',
    acceptance: '场景模型页能完成体验型 UI 流程。',
  },
  {
    group: '技能开发 / 技能生产',
    title: '功能概述',
    docPath: 'cmnssc22s',
    imageCount: 1,
    auditEvidence: '已读取正文和 1 张截图；提炼为技能生产生命周期概述。',
    platform: 'studio',
    mappedRoutes: ['/studio/workspace/orchestrate', '/studio/workspace/repository'],
    coverage: 'covered',
    gap: '已在快速开始、编排、技能仓库、评测、API 管理和离线部署中串联技能生命周期。',
    implementation: '在快速开始和技能仓库中以流程步骤展示创建、评测、发布、部署。',
    priority: 'P0',
    acceptance: '用户能理解技能从草稿到视觉应用/API/离线部署的路径。',
  },
  {
    group: '技能开发 / 技能生产',
    title: '创建技能',
    docPath: 'jmnssc29d',
    imageCount: 3,
    auditEvidence: '已读取正文和 3 张截图；确认入口先创建技能弹窗，再点卡片进画布。',
    platform: 'studio',
    mappedRoutes: ['/studio/workspace/orchestrate'],
    coverage: 'covered',
    gap: '已在编排入口和创建向导中展示名称、描述、标签、配图、版本号、视觉应用/API/离线部署发布渠道。',
    implementation: '扩展编排页的基础信息和发布动作说明。',
    priority: 'P1',
    acceptance: '创建向导能表达基础信息、标签、版本、发布渠道。',
  },
  {
    group: '技能开发 / 技能生产',
    title: '技能编排节点',
    docPath: 'dmnssc2ie',
    imageCount: 18,
    auditEvidence: '已读取正文和 18 张截图；节点包括开始、模型、处理、判断、结束及输入输出引用。',
    platform: 'studio',
    mappedRoutes: ['/studio/workspace/orchestrate'],
    coverage: 'covered',
    gap: '已在 orchestrate-flow 常量与编排画布中补齐开始、视觉模型、多模态、处理、判断、结束节点参数。',
    implementation: '在 orchestrate-flow 常量中补齐多模态、处理、判断、结束节点参数文案。',
    priority: 'P0',
    acceptance: '节点配置能覆盖开始、视觉模型、多模态、处理、判断、结束。',
  },
  {
    group: '技能开发 / 技能生产',
    title: '技能编排常见问题',
    docPath: 'Smnssc278',
    imageCount: 0,
    auditEvidence: '已读取在线正文；无截图，FAQ 合并为编排校验和节点帮助。',
    platform: 'studio',
    mappedRoutes: ['/studio/workspace/orchestrate'],
    coverage: 'merged',
    gap: 'FAQ 不适合拆成独立菜单。',
    implementation: '合并为节点配置帮助文案和校验提示。',
    priority: 'P2',
    acceptance: '编排相关页面能提示持续时间、缓冲时间、追踪判断差异。',
  },
  {
    group: '技能开发 / 技能生产',
    title: '技能版本管理',
    docPath: 'mmnssc2g0',
    imageCount: 7,
    auditEvidence: '已读取正文和 7 张截图；覆盖版本、预发布、正式发布、API 下线、导出。',
    platform: 'studio',
    mappedRoutes: ['/studio/workspace/repository'],
    coverage: 'covered',
    gap: '已在技能仓库展示版本、发布渠道、API 状态、视觉应用状态、离线包状态和版本生命周期。',
    implementation: '扩展技能仓库表格列和详情抽屉信息。',
    priority: 'P0',
    acceptance: '技能仓库能展示版本、渠道、API 状态、视觉应用状态、离线包状态。',
  },
  {
    group: '技能开发 / 技能生产',
    title: '技能效果评测',
    docPath: 'Mmnssc24z',
    imageCount: 10,
    auditEvidence: '已读取正文和 10 张截图；覆盖评测集、抽帧、TP/FP/FN/TN、跨版本对比。',
    platform: 'studio',
    mappedRoutes: ['/studio/workspace/evaluate'],
    coverage: 'covered',
    gap: '已在技能评测页展示评测集、抽帧样本、TP/FP/TN/FN、精确率、召回率、准确率和跨版本流程。',
    implementation: '扩展评测配置列和流程说明。',
    priority: 'P0',
    acceptance: '评测页展示数据集、混淆矩阵指标、召回率、准确率、精确率。',
  },
  {
    group: '技能开发 / 技能生产',
    title: '发布技能API',
    docPath: 'zmnssc2bn',
    imageCount: 7,
    auditEvidence: '已读取正文和 7 张截图；覆盖发布 API、API Key、metadata、run 和监控。',
    platform: 'studio',
    mappedRoutes: ['/studio/workspace/api-management'],
    coverage: 'covered',
    gap: '已新增 API 管理配置页，展示 API Key、Endpoint、metadata/run、输入类型、调用量、成功率、延迟和错误码。',
    implementation: '新增 API 管理配置页。',
    priority: 'P0',
    acceptance: 'API 管理页展示 Key、Endpoint、调用量、成功率、延迟和错误码。',
  },
  {
    group: '技能开发 / 技能生产',
    title: '技能离线部署',
    docPath: '5mnssc2du',
    imageCount: 4,
    auditEvidence: '已读取正文和 4 张截图；覆盖 tar 导出、任务中心、设备指纹、授权文件。',
    platform: 'studio',
    mappedRoutes: ['/studio/workspace/offline-deploy'],
    coverage: 'covered',
    gap: '已新增离线部署配置页，展示离线包导出、任务中心下载、设备指纹、授权文件和边缘盒子部署状态。',
    implementation: '新增离线部署配置页。',
    priority: 'P1',
    acceptance: '离线部署页能展示导出任务、授权额度、设备指纹和部署状态。',
  },
  {
    group: '技能开发 / 模型训练',
    title: '功能概述',
    docPath: 'mmnssc2l3',
    imageCount: 0,
    auditEvidence: '已读取在线正文；无截图，作为模型训练总流程合并承载。',
    platform: 'studio',
    mappedRoutes: ['/studio/workspace/model-train/tasks'],
    coverage: 'merged',
    gap: '概述内容应合并到模型训练相关页面。',
    implementation: '用训练任务 flowSteps 表达数据、模板、训练、评估、部署闭环。',
    priority: 'P1',
    acceptance: '模型训练相关页面能串联训练闭环。',
  },
  {
    group: '技能开发 / 模型训练',
    title: '数据集准备',
    docPath: 'Umnssc2pp',
    imageCount: 42,
    auditEvidence: '已读取正文和 42 张截图；覆盖格式、标注、导入、版本、训练集准备。',
    platform: 'studio',
    mappedRoutes: ['/studio/workspace/data/datasets'],
    coverage: 'covered',
    gap: '已在数据集页展示 COCO/CVAT/ImageNet/VQA 格式、导入来源、标注状态、切分比例、质量评分和发布训练集动作。',
    implementation: '扩展数据集配置的来源、格式、标注状态、质量检查字段。',
    priority: 'P1',
    acceptance: '数据集页展示格式、样本量、标注状态、质量评分和入训练集动作。',
  },
  {
    group: '技能开发 / 模型训练',
    title: '使用数据集构建计划',
    docPath: 'jmnssc2wg',
    imageCount: 10,
    auditEvidence: '已读取正文和 10 张截图；覆盖单次/循环、筛选、抽帧、去重、结果。',
    platform: 'studio',
    mappedRoutes: ['/studio/workspace/data/build-plans'],
    coverage: 'covered',
    gap: '已在构建计划页展示单次/循环计划、数据来源、筛选条件、抽帧去重清洗策略、目标数据集和最近执行结果。',
    implementation: '扩展构建计划配置字段与流程步骤。',
    priority: 'P1',
    acceptance: '构建计划页展示计划类型、数据来源、处理策略和执行结果。',
  },
  {
    group: '技能开发 / 模型训练',
    title: '创建模型训练任务',
    docPath: '6mnssc2u8',
    imageCount: 11,
    auditEvidence: '已读取正文和 11 张截图；覆盖训练、转换、组装、评估和产物。',
    platform: 'studio',
    mappedRoutes: ['/studio/workspace/model-train/tasks'],
    coverage: 'covered',
    gap: '已在训练任务页展示数据集切分、阶段进度、GPU 资源、早停轮次、模型转换/组装、评估指标和产出模型包。',
    implementation: '扩展训练任务表格列和详情流程。',
    priority: 'P1',
    acceptance: '训练任务展示阶段、资源、进度、指标和产出模型。',
  },
  {
    group: '技能开发 / 模型训练',
    title: '模型版本管理',
    docPath: '2mnssc2nj',
    imageCount: 10,
    auditEvidence: '已读取正文和 10 张截图；覆盖模型版本、原子模型、转换、组装包。',
    platform: 'studio',
    mappedRoutes: ['/studio/workspace/model-repository'],
    coverage: 'covered',
    gap: '已在模型仓库页展示版本切换语义、原子模型、转换/组装状态、预后处理、指标和运行环境。',
    implementation: '扩展模型仓库列与详情信息。',
    priority: 'P1',
    acceptance: '模型仓库展示版本、指标、运行环境、转换/组装状态。',
  },
  {
    group: '技能开发 / 模型训练',
    title: '部署自定义推理服务',
    docPath: 'imnssc2s0',
    imageCount: 6,
    auditEvidence: '已读取正文和 6 张截图；覆盖推理服务部署、卸载、日志和资源监控。',
    platform: 'studio',
    mappedRoutes: ['/studio/workspace/inference'],
    coverage: 'covered',
    gap: '已在推理服务页展示部署状态机、QPS、成功率、延迟、CPU/GPU/显存资源占用、失败日志和卸载/扩缩容操作。',
    implementation: '扩展推理服务配置的状态、监控指标和操作记录。',
    priority: 'P1',
    acceptance: '推理服务页展示部署状态、QPS、成功率、延迟和资源占用。',
  },
  {
    group: '技能开发',
    title: '数据湖',
    docPath: '9mnssc1jm',
    imageCount: 10,
    auditEvidence: '已读取正文和 10 张截图；覆盖导入来源、标签、预览、加入数据集。',
    platform: 'studio',
    mappedRoutes: ['/studio/lake'],
    coverage: 'covered',
    gap: '已有数据湖页面，可继续增强导入来源、标签和加入数据集。',
    implementation: '在现有数据湖页补齐导入、本地/BOS、标签、筛选、预览、加入数据集。',
    priority: 'P1',
    acceptance: '数据湖能表达原始资产池到数据集的转化。',
  },
  {
    group: '技能开发',
    title: '工作空间管理',
    docPath: 'lmnssc1ln',
    imageCount: 9,
    auditEvidence: '已读取正文和 9 张截图；覆盖默认空间、成员、角色、配额和删除确认。',
    platform: 'studio',
    mappedRoutes: ['/studio/workspace/space'],
    coverage: 'covered',
    gap: '已在空间管理页展示默认空间、自定义空间、成员角色、空间管理员/开发者/标注员、资源配额、可见资源和删除强确认。',
    implementation: '扩展空间管理配置字段。',
    priority: 'P1',
    acceptance: '空间管理展示成员、角色、配额和资源可见范围。',
  },
  {
    group: '技能开发',
    title: '用户权限',
    docPath: 'fmnssc1no',
    imageCount: 9,
    auditEvidence: '已读取正文和 9 张截图；覆盖用户、组织、角色和 Studio 角色边界。',
    platform: 'studio',
    mappedRoutes: ['/studio/system/user', '/studio/system/org', '/studio/system/role'],
    coverage: 'covered',
    gap: '技能平台角色不可自定义的差异说明不足。',
    implementation: '复用共享系统页，在对标页说明 Studio 权限边界。',
    priority: 'P2',
    acceptance: '用户能区分平台级权限和工作空间权限。',
  },
  {
    group: '视觉应用 / 快速开始',
    title: 'AI分析你的巡检图片、视频',
    docPath: 'hmnssc1t1',
    imageCount: 14,
    auditEvidence: '已读取正文和 14 张截图；覆盖上传文件、分析计划、任务、事件、统计。',
    platform: 'vision',
    mappedRoutes: ['/vision/analysis/view-files', '/vision/analysis/plan', '/vision/analysis/analysis-tasks', '/vision/analysis/events'],
    coverage: 'covered',
    gap: '已新增分析任务、事件记录和统计概览页面，覆盖文件上传、计划、任务、事件、统计和通知闭环。',
    implementation: '新增分析任务、分析事件和分析统计页面。',
    priority: 'P0',
    acceptance: '视图分析能覆盖文件、计划、任务、事件、统计、通知。',
  },
  {
    group: '视觉应用 / 快速开始',
    title: '将已有摄像头变为智能摄像头',
    docPath: '5mnssc1v9',
    imageCount: 15,
    auditEvidence: '已读取正文和 15 张截图；覆盖设备、点位、技能、运行计划、预警。',
    platform: 'vision',
    mappedRoutes: ['/vision/asset/device', '/vision/asset/point', '/vision/asset/skills', '/vision/monitor/skill-plan'],
    coverage: 'covered',
    gap: '已在设备管理页新增已有摄像头智能化向导，串联设备接入、点位、技能、运行计划、预警闭环并提供模块跳转。',
    implementation: '在对标页和相关页面中展示设备接入、点位、技能、运行计划、预警处理流程。',
    priority: 'P1',
    acceptance: '用户能从设备接入跳转到技能运行计划。',
  },
  {
    group: '视觉应用',
    title: '设备接入',
    docPath: '3mnssc148',
    imageCount: 22,
    auditEvidence: '已读取正文和 22 张截图；覆盖 GB/T28181、RTSP、RTMP、点位和异常监控。',
    platform: 'vision',
    mappedRoutes: ['/vision/asset/device', '/vision/asset/point', '/vision/asset/gb-platform'],
    coverage: 'covered',
    gap: '已在设备管理页补齐 GB/T28181、RTSP、RTMP 协议字段、接入测试、自动建点和异常监控表达。',
    implementation: '增强设备接入页面中的 GB/T28181、RTSP、RTMP、在线检测和自动建点说明。',
    priority: 'P0',
    acceptance: '设备接入相关页面能表达三类接入方式和设备/点位关系。',
  },
  {
    group: '视觉应用',
    title: '获取技能',
    docPath: '4mnssc1an',
    imageCount: 7,
    auditEvidence: '已读取正文和 7 张截图；覆盖技能广场添加、Studio 发布、导入包、升级回滚。',
    platform: 'vision',
    mappedRoutes: ['/vision/asset/skills'],
    coverage: 'covered',
    gap: '已在技能资产页展示技能广场添加、Studio 发布、本地技能包导入，以及安装、升级、停用、导出和回滚生命周期。',
    implementation: '增强技能资产页的来源、版本、安装、升级、停用、导入导出字段。',
    priority: 'P0',
    acceptance: '技能页展示三种来源和安装/升级/停用状态。',
  },
  {
    group: '视觉应用',
    title: '视频监控',
    docPath: 'umnssc1cs',
    imageCount: 12,
    auditEvidence: '已读取正文和 12 张截图；覆盖组织树、分屏、抓图、录像、回放导出。',
    platform: 'vision',
    mappedRoutes: ['/vision/video/live', '/vision/video/record-plan'],
    coverage: 'covered',
    gap: '视频模块已有，需持续完善 PTZ、抓图、录制、回放、导出等操作表达。',
    implementation: '保持现有视频页面，补强按钮和状态文案。',
    priority: 'P1',
    acceptance: '视频监控页面能展示分屏、预览、录像计划和回放导出入口。',
  },
  {
    group: '视觉应用',
    title: '监测预警',
    docPath: 'rmnssc1ew',
    imageCount: 35,
    auditEvidence: '已读取正文和 35 张截图；覆盖运行计划、预警通知、记录、复判、档案。',
    platform: 'vision',
    mappedRoutes: ['/vision/monitor/camera', '/vision/monitor/skill-plan', '/vision/monitor/alarm-record', '/vision/monitor/ai-review', '/vision/monitor/alarm-archive'],
    coverage: 'covered',
    gap: '预警页面较完整，计划配置中 ROI、合并、复判、归档策略仍可增强。',
    implementation: '强化技能运行计划和预警记录状态字段。',
    priority: 'P1',
    acceptance: '运行计划覆盖技能、点位、周期、抽帧、ROI、等级、通知和复判。',
  },
  {
    group: '视觉应用',
    title: 'SOP合规分析',
    docPath: 'wmnssc16d',
    imageCount: 16,
    auditEvidence: '已读取正文和 16 张截图；覆盖 SOP 规则、实时监控、非标告警、统计。',
    platform: 'vision',
    mappedRoutes: ['/vision/sop/live', '/vision/sop/rules', '/vision/sop/nonstandard-alarm', '/vision/sop/statistics'],
    coverage: 'covered',
    gap: 'SOP 页面已有，规则步骤、岗位、顺序、超时和统计维度可继续增强。',
    implementation: '强化 SOP 规则与统计页面字段。',
    priority: 'P1',
    acceptance: 'SOP 能表达规则、步骤、合规要求、实时跟踪、非标预警和统计。',
  },
  {
    group: '视觉应用',
    title: '视图分析',
    docPath: 'cmnssc1h4',
    imageCount: 15,
    auditEvidence: '已读取正文和 15 张截图；覆盖视图文件、分析计划、任务、事件、通知。',
    platform: 'vision',
    mappedRoutes: ['/vision/analysis/view-files', '/vision/analysis/plan', '/vision/analysis/analysis-tasks', '/vision/analysis/events', '/vision/analysis/statistics'],
    coverage: 'covered',
    gap: '已新增分析任务、事件记录和统计概览页面，并接入 Vision 视图分析导航闭环。',
    implementation: '新增三个轻量页面，复用 Vision 分析分组。',
    priority: 'P0',
    acceptance: '导航中能访问视图文件、分析计划、分析任务、事件记录、统计概览、应用通知。',
  },
  {
    group: '视觉应用',
    title: '用户权限',
    docPath: 'Xmnssc18k',
    imageCount: 10,
    auditEvidence: '已读取正文和 10 张截图；覆盖 Vision 功能权限和数据权限。',
    platform: 'vision',
    mappedRoutes: ['/vision/system/user', '/vision/system/org', '/vision/system/role'],
    coverage: 'covered',
    gap: '缺少设备、点位、视频查看、告警处理等 Vision 数据权限说明。',
    implementation: '复用共享系统页，在对标页说明 Vision 角色数据范围。',
    priority: 'P2',
    acceptance: '用户能理解 Vision 角色需要配置功能权限和数据权限。',
  },
  {
    group: '多用户访问控制',
    title: '多用户访问控制',
    docPath: 'dmnssc0ru',
    imageCount: 26,
    auditEvidence: '已读取正文和 26 张截图；覆盖主账号、子用户、授权、登录和二次验证。',
    platform: 'shared',
    mappedRoutes: ['/studio/system/security-auth', '/vision/system/security-auth', '/studio/explore/comparison'],
    coverage: 'covered',
    gap: '已在安全认证页展示主账号、子用户、控制台授权、访问方式、平台登录、API Key、AccessKey 和双因素验证说明。',
    implementation: '在安全认证和对标页集中说明。',
    priority: 'P2',
    acceptance: '安全认证页能承载 API Key 和多用户访问控制说明。',
  },
  {
    group: 'API参考',
    title: 'API功能更新记录',
    docPath: 'Kmo8cfnza',
    imageCount: 0,
    auditEvidence: '已读取在线正文；无截图，覆盖 API 更新记录和视频输入更新。',
    platform: 'studio',
    mappedRoutes: ['/studio/workspace/api-reference'],
    coverage: 'covered',
    gap: '已在 API 管理页和 API 参考页展示 API 更新记录、视频输入参数、metadata 与 run 接口能力。',
    implementation: '在 API 管理页展示更新记录和支持的输入类型。',
    priority: 'P0',
    acceptance: 'API 管理页体现视频输入和 metadata schema 能力。',
  },
  {
    group: 'API参考',
    title: '通用说明',
    docPath: 'Omo8comtf',
    imageCount: 4,
    auditEvidence: '已读取在线正文；4 张图片均为公共导航图标，正文覆盖 API Key 鉴权、请求头、HTTP/HTTPS、JSON UTF-8、服务域名和错误码。',
    platform: 'studio',
    mappedRoutes: ['/studio/workspace/api-reference'],
    coverage: 'covered',
    gap: '已在 API 参考页补齐 API Key 鉴权、endpoint、JSON UTF-8、请求/响应结构与错误码说明。',
    implementation: '在 API 参考页“通用说明”标签集中展示鉴权、服务域名、请求响应结构和通用错误码。',
    priority: 'P0',
    acceptance: '页面展示 Authorization Bearer、Endpoint、错误码与调用规范。',
  },
  {
    group: 'API参考',
    title: '技能相关接口',
    docPath: 'Hmnssc1q9',
    imageCount: 8,
    auditEvidence: '已读取在线正文；8 张图片中 4 张为公共导航图标、4 张为 metadata/run 与数据类型业务示意图，正文覆盖使用流程、metadata、run、图片/视频输入、数据类型和 FAQ。',
    platform: 'studio',
    mappedRoutes: ['/studio/workspace/api-reference'],
    coverage: 'covered',
    gap: '已在 API 参考页补齐 metadata 与 run 调用流程、动态 schema value 转义规则、图片/视频输入示例、数据类型和 FAQ。',
    implementation: '在 API 参考页“技能相关接口”标签集中展示 metadata、run、schema 参数、调用示例、错误码、数据类型与常见问题。',
    priority: 'P0',
    acceptance: '页面能说明先获取 metadata，再按 schema 调用 run。',
  },
];

export const yijianCoverageLabels: Record<YijianCoverage, string> = {
  covered: '已覆盖',
  partial: '部分覆盖',
  missing: '缺失',
  merged: '合并承载',
};

export const yijianCoverageColors: Record<YijianCoverage, string> = {
  covered: 'green',
  partial: 'blue',
  missing: 'red',
  merged: 'purple',
};

export const yijianPriorityColors: Record<YijianPriority, string> = {
  P0: 'red',
  P1: 'orange',
  P2: 'default',
};
